apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    CREATE TABLE items (id SERIAL PRIMARY KEY);
    INSERT INTO items DEFAULT VALUES;
    INSERT INTO items DEFAULT VALUES;
    INSERT INTO items DEFAULT VALUES;
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:17
    env:
    - name: POSTGRES_PASSWORD
      value: testpass
    - name: POSTGRES_DB
      value: testdb
    ports:
    - containerPort: 5432
    volumeMounts:
    - name: init
      mountPath: /docker-entrypoint-initdb.d
  volumes:
  - name: init
    configMap:
      name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
