# Simple schema server that serves Cube.js schemas via HTTP
apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-config
data:
  schema.js: |
    cube('Items', {
      sql: `SELECT * FROM items`,
      measures: {
        count: { type: 'count' },
      },
      dimensions: {
        id: { sql: 'id', type: 'number', primaryKey: true },
      },
    });
---
apiVersion: v1
kind: Pod
metadata:
  name: schema-server
  labels:
    app: schema-server
spec:
  containers:
  - name: server
    image: node:20-alpine
    ports:
    - containerPort: 8080
    command: ["node", "-e"]
    args:
    - |
      const http = require('http');
      const fs = require('fs');
      const schema = fs.readFileSync('/schemas/schema.js', 'utf8');
      const schemas = [{ fileName: 'Items.js', content: schema }];
      http.createServer((req, res) => {
        res.writeHead(200, {'Content-Type': 'application/json'});
        res.end(JSON.stringify(schemas));
      }).listen(8080, () => console.log('Schema server on 8080'));
    volumeMounts:
    - name: schemas
      mountPath: /schemas
  volumes:
  - name: schemas
    configMap:
      name: schema-config
---
apiVersion: v1
kind: Service
metadata:
  name: schema-server
spec:
  selector:
    app: schema-server
  ports:
  - port: 8080
